[webdav]
type = webdav
url = https://cloud.ilabt.imec.be/remote.php/dav/files/e809be8a-404e-103b-8b7a-b54d1bec460a
vendor = nextcloud
user = sferraro
pass = CQX1pJyWJpFEOIZB9D__ppKn2Bkd3g2-gvyBnWOjlQ

