# @package _global_
obs_type: pixels
action_repeat: 2 
encoder: {mlp_keys: 'proprio', cnn_keys: 'rgb|depth', norm: none, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: [400, 400, 400, 400]} # act: elu
decoder: {mlp_keys: 'proprio', cnn_keys: '$^', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]} # act: elu
object_decoder: {mlp_keys: 'objects_pos', cnn_keys: 'rgb|depth|segmentation', norm: none, cnn_depth: 72, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]} # act: elu
replay.capacity: 5e5
# env param
env:
  horizon: 250
  controller: "OSC_POSE" # "pd_ee_delta_pos" #     
  renderer:
    fps: 30
    size: [64, 64]
    camera: "base_camera" # "frontview", "agentview", "eye_in_hand" for robosuite | "base_camera" for maniskill
    depths: True
    segmentation_level: "element" # None, class, instance or element 
  reward_shaping: False
  objects:
    rgba: [1, 0, 0, 1]
    minsize: 0.04
    spawn_range: 0.001
    name: "035_power_drill" # "003_cracker_box" 
  goal:
    x: None
    y: None
    z: None
    point_goal: False
comment: ""
