task: "Stack"
horizon: 250
renderer:
  fps: 30
  size: [64, 64]
  cameras: ["frontview", "agentview", "eye_in_hand"]
  depths: True
  segmentation_level: "class" # None, class, instance or element
reward_shaping: true
objects: ["cubeA", "cubeB"]

