defaults:
  - segmenter
  
name: ms
horizon: 250
controller: "pd_ee_delta_pos"
renderer:
  fps: 30
  size: [64, 64]
  camera: "base_camera"
  depths: True
  segmentation_level: "element" # None, class, instance or element 
  seg_size: [256, 256]
  gt_segmentation: True
reward_shaping: False
task_reward: "turn"
objects:
  rgba: [1, 0, 0, 1]
  minsize: 0.04
  spawn_range: 0.01
  random_placement: False
  name: "035_power_drill" # "003_cracker_box" 
goal:
  x: None
  y: None
  z: None
  point_goal: False
  
init_exploration_area: [0.05, 0.84]

