defaults:
  - segmenter

name: mw
horizon: 250
controller: "OSC_POSE" 
renderer:
  fps: 30
  size: [64, 64]
  camera: "corner3" # "corner2" "corner3" "topview"
  depths: True
  segmentation_level: "element" # None, class, instance or element 
  seg_size: [480, 480]
  gt_segmentation: True
reward_shaping: False
task_reward: "pick-place"
objects:
  rgba: [1, 0, 0, 1]
  minsize: 0.025
  spawn_range: 0.01
  random_placement: False
  name: ""  
goal:
  x: None
  y: None
  z: None
  point_goal: False
  
init_exploration_area: [[-0.05, 0.05], [-0.05, 0.05], [0, 0]]
limits_exploration_area: [[-0.35, 0.35], [-0.1, 0.4], [0, 0.03]] # removed z axis for ease of testing
object_start_pos: [0, 0.5, 0] 

visualize_target: True
dist_as_rw: False
target_ablation_diam: False


