defaults:
  - segmenter

name: mw
horizon: 250
controller: "OSC_POSE" 
renderer:
  fps: 30
  size: [64, 64]
  camera: "corner2" # "corner2" "corner3" "topview"
  depths: True
  segmentation_level: "element" # None, class, instance or element 
  seg_size: [480, 480]
  gt_segmentation: False
reward_shaping: False
task_reward: "pick-place"
objects:
  rgba: [1, 0, 0, 1]
  minsize: 0.025
  spawn_range: 0.01
  random_placement: False
  name: ""  
goal:
  x: None
  y: None
  z: None
  point_goal: False
