# Dreamer defaults
actor: {layers: 4, units: 400, norm: none, dist: trunc_normal, min_std: 0.1 } # act: elu 
critic: {layers: 4, units: 400, norm: none, dist: mse} # act: elu, 
actor_opt: {opt: adam, lr: 8e-5, eps: 1e-5, clip: 100, wd: 1e-6}
critic_opt: {opt: adam, lr: 8e-5, eps: 1e-5, clip: 100, wd: 1e-6}
reward_coeff: {rw_sup: 0.0, rw_mov: 0.0, rw_dist_obj: -1.0, rw_intr: 1.0} 
clip_rewards: identity
discount: 0.99
discount_lambda: 0.95
actor_grad: dynamics
slow_target: True
slow_target_update: 100
slow_target_fraction: 1
slow_baseline: True

apt: 
  knn_rms: False 
  knn_k: 30
  knn_avg: True 
  knn_clip: 0.0001