defaults:
  - default

_target_: agent.focus_pcp.FocusPCPAgent
name: focus_pcp
cfg: ???
obs_space: ???
act_spec: ???
reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
reward_fn: "pos"
actor_ent: 0
skill_reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}

train_target_reach: True
symlog_inputs: True # integration from DreamerV3

world_model:
  encoder: {mlp_keys: 'proprio|objects_pos', cnn_keys: 'rgb', norm: none, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: 4, mlp_units: 400, coordConv: False} # act: elu
  decoder: {mlp_keys: 'proprio', cnn_keys: '$^', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: 4, mlp_units: 400} # act: elu
  object_decoder: {mlp_keys: 'objects_pos', cnn_keys: 'rgb|segmentation', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: 4, mlp_units: 400} # act: elu
  object_extractor: {norm: none, act: 'ReLU', layers: 2, units: 512, dist: "mse"}
  grad_heads: [decoder, object_decoder]
  objects: []
  device: cuda
  name: focus
