# @package agent
defaults:
  - default

_target_: agents.icm.ICMDreamerAgent
name: icm_dreamer
cfg: ???
obs_space: ???
act_spec: ???
reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
actor_ent: 0 
icm_scale: 1.0