defaults:
  - default

_target_: agent.skill_focus.SkillFocusAgent
name: skill_focus
cfg: ???
obs_space: ???
act_spec: ???
reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
actor_ent: 0
skill_reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
train_target_reach: True
distance_mode: 'mse'
start_agent_training_after: 10 #2500
only_expl_during_training: True

world_model:
  encoder: {mlp_keys: '$^', cnn_keys: 'rgb', norm: none, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: [400, 400, 400, 400], coordConv: False} # act: elu
  decoder: {mlp_keys: '$^', cnn_keys: '$^', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]} # act: elu
  object_encoder: {mlp_keys: 'objects_pos', cnn_keys: '$^', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400], distance_mode: "cosine", act: 'ReLU'} 
  object_decoder: {mlp_keys: 'objects_pos', cnn_keys: 'rgb|segmentation', norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]} # act: elu
  object_extractor: {norm: none, act: 'ReLU', mlp_layers: [512, 512], obj_latent_as_dist: False}
  grad_heads: [decoder, object_decoder]
  replay.capacity: 5e5
  objEnc_MSE_ratio: 0.975
  objects: [] 
  device: cuda
  name: focus