_target_: agent.td3.TD3Agent
name: td3_bc
obs_space: ???
act_spec: ???
device: ${device}
lr: 3e-4 # 1e-4 in ExORL
hidden_dim: 1024
feature_dim: 50
# actor critic
stddev_schedule: 0
stddev_clip: 0.3 # 0.5 in SpinningUp
# nstep: 3 # TODO: not used rn
policy_delay: 2
distributional: false
target_tau: 0.005 # 0.005 in SpinningUp # 0.01 in EXORL
bc_alpha: 2.5 # 2.5 is good for TD3+BC
# encoder
obs_keys: rgb|proprio
drq_encoder: True
drq_aug: false
